apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: php-training
data:
  apache.conf: |
    <VirtualHost *:80>
      ServerAdmin bruce.dts@gmail.com
      DocumentRoot /srv/app/public
      <Directory "/srv/app/public">
        AllowOverride all
        Require all granted
      </Directory>
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
    </VirtualHost>
  php.ini: |
    date.timezone = Brazil/East
    [opcache]
    opcache.enable=1
    opcache.revalaidate_freq=0
    opcache.fast_shutdown=1
    opcache.validate_timestamps=1
    opcache.max_accelerated_files=6000
    opcache.interned_strings_buffer=16
  xdebug.ini: |
    [xdebug]
    xdebug.default_enable = ${PHP_XDEBUG_DEFAULT_ENABLE}
    xdebug.remote_autostart = ${PHP_XDEBUG_REMOTE_AUTOSTART}
    ; remote_connect_back is not safe in production! 
    xdebug.remote_connect_back = ${PHP_XDEBUG_REMOTE_CONNECT_BACK}
    xdebug.remote_port = ${PHP_XDEBUG_REMOTE_PORT}
    xdebug.remote_enable = ${PHP_XDEBUG_REMOTE_ENABLE}
    xdebug.idekey = ${PHP_XDEBUG_IDEKEY}
    xdebug.remote_host = ${PHP_XDEBUG_REMOTE_HOST}
    ; profiling
    xdebug.profiler_enable = ${PHP_XDEBUG_PROFILER_ENABLE}
    xdebug.profiler_output_dir = ${PHP_XDEBUG_PROFILER_OUTPUT_DIR}
