version: "3"
services:
 app:
  image: bruceemmanuel/php-web-env:1.1
  depends_on:
   - mysql
  ports:
   - "8001:80"
  volumes:
   - .:/srv/app
  links:
   - mysql:db
  env_file: .docker.env
 mysql:
  image: mysql:5.7
  volumes:
    - ./storage/mysql:/var/lib/mysql
  ports:
   - "13306:3306"
  environment:
   - MYSQL_DATABASE=zce
   - MYSQL_ROOT_PASSWORD=root
